openapi: "3.0.0"
info:
  title: ICanHazDadJoke APIM Wrapper
  description: An APIM Wrapper around the ICanHazDadJoke api
  version: "1.0.0"
paths:
  /:
    get:
      operationId: getRandomJoke
      summary: Get a Random dad joke
      responses:
        '200':
          description: |-
            200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/singleJokeResponse'
              examples:
                default:
                  value: 
                    {
                      "id": "R7UfaahVfFd",
                      "joke": "My dog used to chase people on a bike a lot. It got so bad I had to take his bike away.",
                      "status": 200
                    }
  /search:
    post:
      operationId: searchForJokes
      summary: Search for dad jokes
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/searchRequest'
      responses:
        '200':
          description: |-
            200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/searchResponse'
              examples:
                default:
                  value: 
                    {
                      "current_page": 1,
                      "limit": 20,
                      "next_page": 2,
                      "previous_page": 1,
                      "results": [
                        {
                          "id": "M7wPC5wPKBd",
                          "joke": "Did you hear the one about the guy with the broken hearing aid? Neither did he."
                        },
                        {
                          "id": "MRZ0LJtHQCd",
                          "joke": "What do you call a fly without wings? A walk."
                        },
                        {
                          "id": "usrcaMuszd",
                          "joke": "What's the worst thing about ancient history class? The teachers tend to Babylon."
                        }
                      ],
                      "search_term": "",
                      "status": 200,
                      "total_jokes": 307,
                      "total_pages": 15
                    }
components:
  schemas:
    searchRequest:
      type: object
      properties:
        page:
          type: integer
        limit:
          type: integer
        term:
          type: string
    singleJokeResponse:
      type: object
      properties:
        id:
          type: string
        joke:
          type: string
        term:
          type: integer
    searchResponse:
      type: object
      properties:
        current_page:
          type: integer
        limit:
          type: integer
        next_page:
          type: integer
        previous_page:
          type: integer
        results:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              joke:
                type: string
        search_term:
          type: string
        status:
          type: integer
        total_jokes:
          type: integer
        total_pages:
          type: integer


