name: 'Deploy API to Azure'

on: 
  push:
    branches:
      - main
jobs:
  build_templates: 
    name: Build ARM templates from yaml
    runs-on: windows-latest
    env:
      APIM_RESOURCE_KIT_URI: 'https://github.com/Azure/azure-api-management-devops-resource-kit/archive/refs/tags/v0.6.zip'
      EXTRACTED_PROJECT_PATH: '.\apim_rk\v0.6\azure-api-management-devops-resource-kit-0.6\src\APIM_ARMTemplate\apimtemplate\apimtemplate.csproj'
    steps:
      - uses:  actions/checkout@v1
      - name: Setup dotnet '3.1.x'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Download latest APIM Resource Kit
        shell: pwsh
        run: |
          mkdir apim_rk
          cd apim_rk
          mkdir v0.6
          Invoke-WebRequest ${{env.APIM_RESOURCE_KIT_URI}} -outfile .\archive.zip
          Expand-Archive -LiteralPath ".\archive.zip" -DestinationPath ".\v0.6" -Force
          cd ..
          mkdir templates
      - name: Generate the ARM templates using the tool
        run: dotnet run create --configFile api.yaml --project ${{env.EXTRACTED_PROJECT_PATH}} -c "Release"
      - name: Upload the built ARM templates
        uses: actions/upload-artifact@main
        with:
          name: armtemplates
          path: templates
         
      
  deploy_templates:
    name: Deploy ARM templates
    needs: build_templates
    runs-on: windows-latest
    steps:
      - uses: actions/download-artifact@main
        name: Download Templates
        with: 
          name: armtemplates
          path: templates
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 
      - name: Deploy the Backends
        run: az deployment group create -g 'apim-kv-pl' --template-file ".\templates\mfapim-backends.template.json" --parameters ApimServiceName=mfapim
      - name: Deploy the API
        run: az deployment group create -g 'apim-kv-pl' --template-file ".\templates\ICanHazDadJoke.api.template.json" --parameters ApimServiceName=mfapim
      - name: Azure logout
        run: az logout
      
      

